task:
  name: "Test Task"
  description: "Testing Task"
  pathName: '\contento\' 
  user: 'servicio' # empty will ask for it
action:
  command: 'powershell.exe'
  commandArguments: '-File New-TestTask.ps1'
  workingDirectory: 'c:\Projects\contento\lab.powershell\New-ScheduledTask\'
trigger:
  repetitionDurationInDays: "25*12*30"
  repetitionIntervalInMinutes: "24*60"  
